DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID INT PRIMARY KEY, TITLE VARCHAR(255));
DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID INT PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS TOPICS;
CREATE TABLE TOPICS(ID INT PRIMARY KEY, NAME VARCHAR(255));
